version: '2'

networks:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork

services:
  elasticsearch:
    container_name: ga_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - VIRTUAL_HOST=es.goldenagents.tt.di.huc.knaw.nl
      - VIRTUAL_PORT=9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - nginxproxynetwork
    expose:
       - 9200
    # restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 262144

  kibana:
    container_name: ga_kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VIRTUAL_HOST=kibana.goldenagents.tt.di.huc.knaw.nl
    networks:
      - nginxproxynetwork 
    depends_on:
      - elasticsearch